modLoader="javafml"
loaderVersion="[2,)"
license="All Rights Reserved"

[[mods]]
modId="create_custom_lava"
version="1.0.0"
displayName="Create Custom Lava"
authors="Djiker"

description='''
This mod adds a custom lava for Create on NeoForge 1.21.1.

Requires: Create: Dragons Plus

This project is based on the NeoForge 1.21.1 template, with inspiration and learning from:
- Create: Dragons Plus
- Create: Diesel Generators

Through fluid interactions, the following blocks are made renewable:
- Magma Block
- Cobbled Deepslate
- Netherrack
- Calcite
- Scorchia
- Blackstone
- Basalt
- Obsidian
- Amethyst Block
- Terracotta
- Colored Terracotta variants
'''

[[dependencies.create_custom_lava]]
modId="neoforge"
type="required"
versionRange="[21.1,)"
ordering="NONE"
side="BOTH"

[[dependencies.create_custom_lava]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.22)"
ordering="NONE"
side="BOTH"

[[dependencies.create_custom_lava]]
modId="create_dragons_plus"
type="required"
versionRange="[1.0.0,)"
ordering="AFTER"
side="BOTH"
