modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
authors="Djiker"

description='''
This mod adds a custom lava for Create on NeoForge ${minecraft_version}.

Requires: Create: Dragons Plus

This project is based on the NeoForge ${minecraft_version} template, with inspiration and learning from:
- Create: Dragons Plus
- Create: Diesel Generators

Through fluid interactions, the following blocks are made renewable:
- Magma Block
- Cobbled Deepslate
- Netherrack
- Calcite
- Scorchia
- Blackstone
- Basalt
- Obsidian
- Amethyst Block
- Terracotta
- Colored Terracotta variants
'''

[[dependencies."${mod_id}"]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="create_dragons_plus"
type="required"
versionRange="${create_dragons_plus_version_range}"
ordering="AFTER"
side="BOTH"

[[dependencies."${mod_id}"]]
modId="create"
type="required"
versionRange="${create_version_range}"
ordering="AFTER"
side="BOTH"